name: debug_kit_dio
description: "Dio network logging adapter for DebugKit. Automatically logs requests, responses, and errors with sanitization."
version: 0.6.0
repository: https://github.com/iamPedram1/debugkit
issue_tracker: https://github.com/iamPedram1/debugkit/issues
topics:
  - logging
  - dio
  - networking
  - devtools
  - debug-kit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  debug_kit: ^0.11.0
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
